select * from customer

--1->what is the total revenue generated by male vs. female customer?

select gender, sum(purachase_amount) as revenue
from customer
group by gender

--2->which customer used a discount but still spent more than the 
--average purchase amount?

select customer_id, purachase_amount
from customer
where discount_applied = 'Yes' and purachase_amount >= (select AVG(purachase_amount) from customer)


--3->whaich are the top 5 products with the height average review rating?

select top 5  item_purchased , round(avg(review_rating),2) as "Average product rating"
from customer
group by item_purchased
order by AVG(review_rating) desc;

--4->comapre the average purchase amounts between standard and 
--express shipping.

select   shipping_type, round(avg(purachase_amount),2) as "Average purchase amount"
from customer
where shipping_type in ('Express', 'standard')
group by shipping_type;

--5->do subscried customers spend more? compare average spend 
--and total revenue between subscribedamd non-subscribers.

select subscription_status, count(customer_id) as total_customer,
round(avg(purachase_amount),2) as avg_spend,
round(sum(purachase_amount),2) as total_revenue
from customer 
group by subscription_status
order by total_revenue, avg_spend desc; 



--6->which 5 products have the highest percentage of purchase with 
--discount applied?

select  top 5 item_purchased,
round(sum(case when discount_applied = 'Yes' then 1 else 0 end) * 100/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc;

--7->segment customers into New, returning, and Loyal based on their total
--number of previous purchases, and show the count of each segment.

with customer_type as(
select customer_id, previous_purchases,
case
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer
)

select customer_segment, count(*) as "Number of Cutomers"
from customer_type
group by customer_segment;



--8->what are the top 3 most purchased products within each category?

with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3;


--9->Are customers who are repeat buyers (more than 5 previous  purchases)
--are likey to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status; 


--10->what is the revenue contribution of each age group?

select age_group,
sum(purachase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;

